#!/bin/bash
  
export AWS_ACCESS_KEY_ID=AKIARWLGKZUT7JX5E6RF
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-west-2
export LAMBDA_ROLE_ARN=116715605287:role/lambda-role
