#!/bin/bash
  
export AWS_ACCESS_KEY_ID=AKIARWLGKZUT7INFD7V4
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-west-2
export LAMBDA_ROLE_ARN=116715605287:role/lambda-role
